apiVersion: v1
kind: Pod
metadata:
  name: arduino-gcc
spec:
  containers:
    - name: arduino-gcc
      image: artifacts.microchip.com:7999/microchip/mcu8mass/arduino-gcc:latest
      imagePullPolicy: Always
      command: ["cat"]
      tty: true
      resources:
        requests:
          cpu: 0.25
          memory: 500Mi
        limits:
          cpu: 0.5
          memory: 750Mi
